version: '2'
services:
  zookeeper:
    image: mobify/kafka-cluster
    hostname: zookeeper
    ports:
      - "2181"
    environment:
      RUN_TYPE: "zookeeper"
  kafka:
    image: mobify/kafka-cluster
    hostname: kafka
    ports:
      - "9092"
    environment:
      RUN_TYPE: "kafka"
    links:
      - zookeeper
